language: java
notifications:
  email: false
  slack:
    secure: YDOwOIKKvzD8mul49HSTJOYcZZL7DkFnG2q9LfYM9hQuniMc4YcLeAiXH6bhl9qGtah4Hp/rAwD9T/aC8ddrn2j4QoR8vVzhlxViUofmpwnMSyxnqmHG0/nklVq34jD6jJ3tWKTKsOn2WZnNSAyAlO+0FySTX9xWlM1qp/2OeHJblEdnqFoesvoTBFRTeEQbqZ2hLL/LlPgQ69jIDNmUbBF7oLZPgigFalZOSkmOakxrpk9M9voURnHGJ4xYKlYsjP2uQWJvR8L5aKNwnZD1Sch72iwHRFQ1s6WcscSlqApUQ4tzcai4cAD3RpHr4Be+JfWxQXg+xZiURVcfBiyAuOe6GqBb6whMBJ0DUZZktz4xEkatJ5egq2deZHMOX3MEH3Y514LtulraMj1D9rsvksGDvE7wMUbZa0od2FNOig5z6y26ZNpAovqRBcZvTt68R/DJpiuS3sXiTy3nD3vbmAlTbBCDmJ6ASl/qldCtvYHg7dLOMtZY4iopnspC+rgUFmWwS1wA+QMJPlPhoXk2+iEZm4+43l/hjtiv8xfx6gNfkeITpiICMRaf/ruWrmligrrcOUtu+2NI57M1qNS0Qgpo9mEFiHamLsPdWOL/vSeNv+Tmfl1EbzluvfPqrNp5DXim1+Ydx/GyoQxFZ6bh3GcTFPk1ngkY5Ph1kF1FdiA=
install:
  - ./install_dependencies.sh
