language: java
notifications:
  email: false
  slack:
    secure: YDOwOIKKvzD8mul49HSTJOYcZZL7DkFnG2q9LfYM9hQuniMc4YcLeAiXH6bhl9qGtah4Hp/rAwD9T/aC8ddrn2j4QoR8vVzhlxViUofmpwnMSyxnqmHG0/nklVq34jD6jJ3tWKTKsOn2WZnNSAyAlO+0FySTX9xWlM1qp/2OeHJblEdnqFoesvoTBFRTeEQbqZ2hLL/LlPgQ69jIDNmUbBF7oLZPgigFalZOSkmOakxrpk9M9voURnHGJ4xYKlYsjP2uQWJvR8L5aKNwnZD1Sch72iwHRFQ1s6WcscSlqApUQ4tzcai4cAD3RpHr4Be+JfWxQXg+xZiURVcfBiyAuOe6GqBb6whMBJ0DUZZktz4xEkatJ5egq2deZHMOX3MEH3Y514LtulraMj1D9rsvksGDvE7wMUbZa0od2FNOig5z6y26ZNpAovqRBcZvTt68R/DJpiuS3sXiTy3nD3vbmAlTbBCDmJ6ASl/qldCtvYHg7dLOMtZY4iopnspC+rgUFmWwS1wA+QMJPlPhoXk2+iEZm4+43l/hjtiv8xfx6gNfkeITpiICMRaf/ruWrmligrrcOUtu+2NI57M1qNS0Qgpo9mEFiHamLsPdWOL/vSeNv+Tmfl1EbzluvfPqrNp5DXim1+Ydx/GyoQxFZ6bh3GcTFPk1ngkY5Ph1kF1FdiA=
addons:
  sonarcloud:
    organization: isa-group
    token:
      secure: G+YQiLTMWYGtWdA6FI4+7tjv7UbW4ivfNV2Mu7cyZA1eaW4QcArI6x9jetZuKETbVuMSh9Sb5kg4KAsiESnDl+rwV9Aa4Tv2CQ00+uCvi9YDeucqRe/IUYcWIYvsT2QCuq3MdxUyPlXfHtfeOizavzQXDLmJDWtZhvesO5c1zHe1eV5azt0x03UDZ1moDLcDjPLBcabW+GXYzovScOY5GjdGqI7+qgToxMPO1NFFukkhuIPlZ/YxKVAErKYotJpfbWs1tMCT/xUnoZDYXNcn+n/T43lMvk+r6IVXuB20xhUln6SUNnG8B7XtxEFNwIxOfi7uD6uw7N0ZPZqmr7NA/s1lcQjJu5EmsUYSXTz2VnYU5Y/vRFhFuk+GL44HAsUlFlP/Qpg9apSGKYj1J/pVYBjE3Zt4avIwHHis8817vahoedxGHDvL3jjDnNyLc8cLEwt8c9YEhK8yGshy67qkeWgNQqPLYAhvmTmuxQPYzmGGMRPPmFr0iX0cz5QKkTD9FAqAseu+XY3jwo3uB232IcScQ3NaSMWFDn7W6FGnFH3cfACw/ZGutz3o4vxHLGm8oKJ0dx9PqOcgViVLdrhsonOCGeA6ifdwR6ossf4yQlQbAZmXbgMXVF9bMfBHUEmi4wbVemmtWCBcKpB9DQhV6E5Z4H2WMkZhwXRMovpgXgY=
install:
  - ./install_dependencies.sh
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=isa-group_RESTest-search-based
    -Dsonar.projectName=RESTest-search-based -Dsonar.sources=src/main/java -Dsonar.tests=src/test/java
